name: Cache Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: prime-cache-15fe162
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/myapp
          key: cache-15fe162

      - name: Show cache result
        run: echo "Cache result = ${{ steps.cache-step.outputs.cache-hit }}"
